[build-system]
requires = ["setuptools >= 61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "spotify-import"
dynamic = ["version"]
dependencies = [
  "spotipy",
  "thefuzz",
  "beautifulsoup4",
]
readme = "readme.md"
